---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: my-postgresql-cluster
  namespace: default
spec:
  replicas: 3  # Number of PostgreSQL pods in the HA setup
  image: "crunchydata/crunchy-postgres:latest"  # Specify your preferred PostgreSQL image
  port: 5432  # Port for PostgreSQL
  user: postgres  # The default user
  password: yourpassword  # Set the password for the user
  database: mydatabase  # The default database to create
  storage:
    size: 10Gi  # Specify the storage size
    storageClassName: standard  # Ensure this matches the storage class in the PersistentVolume
  standby:
    replicas: 1  # Define how many standby nodes to create
  primary:
    # Optional: define primary node specific settings (e.g., resources, affinity, etc.)
  resources:
    requests:
      memory: "1Gi"
      cpu: "1"
    limits:
      memory: "2Gi"
      cpu: "2"

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
provisioner: kubernetes.io/aws-ebs  # Use this if you are on AWS, change if you're using a different cloud provider
reclaimPolicy: Retain
volumeBindingMode: Immediate
