---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-postgresql-pv
spec:
  capacity:
    storage: 10Gi  # Adjust based on your needs
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard  # Ensure this matches your PVC's storage class
  hostPath:
    path: "/mnt/data/postgresql"  # Adjust based on your environment or use cloud-based storage
  volumeMode: Filesystem  # Specify volume mode, which should typically be 'Filesystem'
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: my-postgresql-cluster
  namespace: default
spec:
  replicas: 3  # Number of PostgreSQL pods in the HA setup
  image: "crunchydata/crunchy-postgres:latest"  # Specify your preferred PostgreSQL image
  port: 5432  # Port for PostgreSQL
  user: postgres  # The default user
  password: yourpassword  # Set the password for the user
  database: mydatabase  # The default database to create
  storage:
    size: 10Gi  # Specify the storage size
    storageClassName: standard  # Define the storage class to match your PV and PVC
  standby:
    replicas: 1  # Define how many standby nodes to create
  primary:
    # Optional: define primary node specific settings (e.g., resources, affinity, etc.)
  resources:
    requests:
      memory: "1Gi"
      cpu: "1"
    limits:
      memory: "2Gi"
      cpu: "2"
