# Namespace definition
---
apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
  labels:
    app: jenkins

# PersistentVolume definition
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  labels:
    app: jenkins
spec:
  capacity:
    storage: 12Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: jenkins-storage
  hostPath:
    path: /mnt/data/jenkins

# PersistentVolumeClaim definition
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: jenkins
  labels:
    app: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 12Gi
  storageClassName: jenkins-storage

# ServiceAccount definition
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-master
  namespace: jenkins

# Role for Jenkins
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-master
  namespace: jenkins
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec", "pods/log", "events", "secrets", "configmaps", "services"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]

# RoleBinding for Jenkins
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-master
  namespace: jenkins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins-master
subjects:
- kind: ServiceAccount
  name: jenkins-master
  namespace: jenkins

# Jenkins Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-master
  namespace: jenkins
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-master
  template:
    metadata:
      labels:
        app: jenkins-master
    spec:
      serviceAccountName: jenkins-master
      securityContext:
        fsGroup: 1000
      initContainers:
      - name: init-jenkins-home
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /var/jenkins_home"]
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        securityContext:
          runAsUser: 1000
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
        env:
        - name: JAVA_OPTS
          value: "-Djenkins.install.runSetupWizard=false"
        - name: JENKINS_OPTS
          value: "--httpPort=8080"
        - name: http_proxy
          value: "http://nginx-proxy.jenkins.svc.cluster.local:80"
        - name: https_proxy
          value: "http://nginx-proxy.jenkins.svc.cluster.local:80"
        - name: no_proxy
          value: "localhost,127.0.0.1,.svc.cluster.local"
        ports:
        - name: http-port
          containerPort: 8080
        - name: jnlp-port
          containerPort: 50000
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
        readinessProbe:
          httpGet:
            path: /login
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /login
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 15
      terminationGracePeriodSeconds: 30
      volumes:
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: jenkins-pvc

# NodePort Service for external access
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-master-nodeport
  namespace: jenkins
spec:
  type: NodePort
  selector:
    app: jenkins-master
  ports:
  - name: jenkins-http
    protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30080
  - name: jenkins-jnlp
    protocol: TCP
    port: 50000
    targetPort: 50000
    nodePort: 30050

# ClusterIP Service for internal access
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-master-clusterip
  namespace: jenkins
spec:
  type: ClusterIP
  selector:
    app: jenkins-master
  ports:
  - name: jenkins-http
    protocol: TCP
    port: 80
    targetPort: 8080
  - name: jenkins-jnlp
    protocol: TCP
    port: 50000
    targetPort: 50000

# Optional LoadBalancer Service (for Cloud environments)
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-master-loadbalancer
  namespace: jenkins
spec:
  type: LoadBalancer
  selector:
    app: jenkins-master
  ports:
  - name: jenkins-http
    protocol: TCP
    port: 80
    targetPort: 8080
  - name: jenkins-jnlp
    protocol: TCP
    port: 50000
    targetPort: 50000

# Create an Nginx Deployment and Service to expose Jenkins properly.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy
  namespace: jenkins
  labels:
    app: nginx-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-proxy
  template:
    metadata:
      labels:
        app: nginx-proxy
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy
  namespace: jenkins
spec:
  selector:
    app: nginx-proxy
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer

# Define the reverse proxy settings for Jenkins.
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: jenkins
data:
  nginx.conf: |
    worker_processes 1;
    events { worker_connections 1024; }

    http {
        server {
            listen 80;


            location / {
                proxy_pass http://jenkins-master-clusterip:80;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Port $server_port;

                proxy_read_timeout 90;
                proxy_connect_timeout 90;
                proxy_send_timeout 90;
                client_max_body_size 100M;

                # Rewrite the Location header in the response
                proxy_redirect http://jenkins-master-clusterip:80/ /;
                proxy_redirect ~^http://(.*)/jenkins/(.*)$ http://$host/jenkins/$2;
            }
        }
    }
