kind: Deployment
apiVersion: apps/v1
metadata:
  name: nfs-client-provisioner
spec:
  replicas: 2  # Increased for higher availability
  strategy:
    type: RollingUpdate  # Ensures smooth updates
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: nfs-client-provisioner
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: registry.k8s.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
          resources:
            requests:
              cpu: "100m"  # Ensures the pod gets scheduled even on busy nodes
              memory: "128Mi"
            limits:
              cpu: "500m"   # Prevents excessive CPU usage
              memory: "256Mi"
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: example.com/nfs
            - name: NFS_SERVER
              value: myip.local
            - name: NFS_PATH
              value: /nfs/kubedata
      volumes:
        - name: nfs-client-root
          nfs:
            server: myip.local
            path: /nfs/kubedata
